package org.oop.secondlab.models;

public enum StudyField {
    MECHANICAL_ENGINEERING,
    SOFTWARE_ENGINEERING,
    FOOD_TECHNOLOGY,
    URBANISM_ARCHITECTURE,
    VETERINARY_MEDICINE,
    TELECOMMUNICATION_SYSTEMS,
    INDUSTRIAL_DESIGN
}
